Queue support (#724)
In order to implement the queue support properly, I found it necessary
to refactor the audio and video playback support. I chose
[react-player](http://npmjs.com/package/react-player) for the video
playback, and was able to make many improvements by updating the
underlying library for audio playback,
[audiosource](http://npmjs.com/package/audiosource) (a module I own).

This is a really large commit, and for that I apologize, much of these
changes are boilerplate, or moving things around. Here is a list of
files with much of the logic responsible for the changes:
* [components/player-view.js](components/player-view.js)
* [components/queue-view.js](components/queue-view.js)
* [components/queue-item.js](components/queue-item.js)
* [client-lib/app-data.js](client-lib/app-data.js)
* [app.js](app.js)
* [index.js](index.js)
* [lib/launch-video.js](lib/launch-video.js)
* [lib/window-utils.js](lib/window-utils.js)
* [lib/youtube-helpers.js](lib/youtube-helpers.js)

Changes Overview
- add queue support #449
- update audio-ctrl for new audiosource api
- change waveform vis to use [gl-waveform](http://npmjs.com/package/gl-waveform)
- add [storybook](http://npmjs.com/package/gl-waveform) for easier ui hacking

(rest of minor changes and bug fixes as a result of the queue
feature/playback refactor are listed below)

Dependencies:

Updated dependencies:
* `testpilot-metrics@2.1.3`
* `audiosource@3.0.2`
* `watchify@3.9.0`

Added dependencies:
* `iso8601-duration@1.0.6`

Added dev-dependencies:
* `@kadira/storybook@2.35.3`
* `babel-preset-es2015@6.22.0`
* `gl-waveform@2.2.6`
* `just-extend@1.1.22`
* `keyboardjs@2.3.3`
* `react-player@0.14.1`
* `react-tabs@0.8.2`
* `sortablejs@1.5.1`
* `storybook-host@.0.14`
* `svgify@0.0.0`
* `svgo-loader@1.1.2`
* `webworkify-webpack@2.0.1`

Removed dependencies:
* `audio-fft@0.1.4`

Effected issues

General fixes:
* Keyboard controls fixes #67
* closed captioning fixes #68
* Volume is incorrectly set when Mute/Unmute actions are made fixes #335
* Min-Vid icon and "Send to mini player" option are missing if the
  browser is in Private Window mode fixes #431
* The volume bar should be hidden when the other controls are hovered
  fixes #358
* evaluate tooltip placement fixes #461
* Min Vid might be making Nightly run slowly fixes #481
* Timestamp and seekbar are not updated with the latest video progress
  if the "Confirm close" window is displayed fixes #472
* How can we differentiate the videos that can be played with Min-Vid
  player from those that cannot be played using a GET request? fixes
  #505
* TypeError: addonInfo is undefined fixes #491
* Wrong timestamp displayed for a second after sending a Vimeo video
  over a playing YouTube one fixes #609
* Correct error is quickly overlapped by another when first sending a
  VEVO video to mini player fixes #605
* "Unmute" message appears for a fraction of a second after sending
  YouTube videos to the mini player fixes #581
* [YouTube] For each video sent to mini player, the sound volume
  increases when lowering the volume slider (above 75%) fixes #568
* Volume slider changes position only after second unmute, if it was
  manually set to 0% previously fixes #567
* Inconsistent default volume level between Youtube and Vimeo &
  Soundcloud when sending content to mini player fixes #565
* The bottom quarter of the progress bar does not react to clicks
  fixes #646
* [Vimeo] Moving the mini player gets progressively worse after fast
  forwarding and backwarding a few times fixes #648
* Remove vine support as scraping methods now fail fixes #666

react-player related fixes:
* The last second of the video is played during "Replay/Close" screen
  fixes #409
* add support for soundcloud playback fixes #445
* Min-Vid seek bar stops showing progress when fast-forwarding with
  keyboard for more than 5 seconds fixes #387
* TypeError: window.YTPlayer.getCurrentTime is not a function fixes
  #469
* Playback stutters when a video is replayed, if YouTube's loop option
  is also enabled fixes #622
* The YouTube overlay appears in the Min Vid player if a specific
  video is sent to it using the context menu option fixes #701

Queue feature:
* Min-vid halts progress on Youtube playlists fixes #417
* basic playlist support (minimal) fixes #449
* Add to queue tooltip for overlay icon + option fixes #634
* Videos occasionally get stuck in loading loop fixes #468
* Looping videos fixes #621
* Sending the same video to the mini player pauses the one that is
  playing fixes #580

Audio Player fixes:
* [Soundcloud] The mini player is unresponsive for a few seconds after
  sending a second song to it fixes #610
* [Soundcloud] The elapsed time is larger than the total time if you
  wait a while before starting playback fixes #604

Partially completed issues:
* Playlist UI refs #453
* make video resizeable refs #69
* link history for min-vid refs #117
* min-vid doesn't trigger a history event refs #470